using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CONTROLJUGADOR : MonoBehaviour
{

    public int velocidad;
    public Rigidbody rb;


    // Start is called before the first frame update
    void Start()
    {
        rb = GetComponent<Rigidbody>();

    }

    // Update is called once per frame
    void Update()
    {
        
    }

    private void FixedUpdate()
    {
        float inputX = Input.GetAxis("Horizontal");
        float inputY = Input.GetAxis("Vertical");

        Vector3 movimiento = new Vector3(inputX * velocidad, inputY * velocidad);

        rb.velocity = movimiento;


    }
}
